# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20180228_1024'),
        ('toomanydaves_auth', '0002_auto_20170904_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='peep',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='network.Peep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
    ]
