# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UPCOMING', 'upcoming'), ('ACTIVE', 'active'), ('ARCHIVED', 'archived')], default='UPCOMING', max_length=20)),
                ('origin', models.CharField(choices=[('INTERNAL', 'internal'), ('EXTERNAL', 'external')], default='INTERNAL', max_length=20)),
            ],
        ),
    ]
