# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170906_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, upload_to='project_logos'),
        ),
    ]
