# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20171020_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='claim',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
