# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171105_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.FileField(blank=True, upload_to='post_cover-photo'),
        ),
    ]
