# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_claim'),
        ('blog', '0007_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='associated_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Project'),
        ),
    ]
