# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_associated_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Peep'),
        ),
    ]
