# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180228_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='associated_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Project'),
        ),
    ]
